branch-defaults:
  master:
    environment: master
    group_suffix: null
global:
  application_name: farie
  branch: null
  default_ec2_keyname: farie
  default_platform: PHP 7.2
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: farie
  repository: null
  sc: git
  workspace_type: Application
